/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    `maven-publish`
    id("com.gradleup.shadow") version "8.3.0"
}

group = "com.clanjhoo"
version = "3.0.0-SNAPSHOT"
description = "DB Framework for bukkit plugins"

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
        vendor = JvmVendorSpec.ORACLE
    }
}

repositories {
    maven("https://papermc.io/repo/repository/maven-public/") {
        content {
            includeGroup("io.papermc.paper")
        }
    }
    maven("https://repo.aikar.co/content/groups/aikar/") {
        content {
            includeGroup("net.md-5")
        }
    }
    //maven("https://oss.sonatype.org/content/groups/public/")
    //maven("https://repo.maven.apache.org/maven2/")
    mavenLocal()
    mavenCentral()
}

dependencies {
    compileOnly("io.papermc.paper:paper-api:1.20.4-R0.1-SNAPSHOT")
    implementation("com.zaxxer:HikariCP:5.1.0") {
        isTransitive = false
    }
    //implementation("org.mariadb.jdbc:mariadb-java-client:3.4.1") {
    //    isTransitive = false
    //}
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}

tasks.processResources {
    filesMatching("**/plugin.yml") {
        expand( project.properties )
    }
}

tasks {
    shadowJar {
        archiveFileName.set("${rootProject.name}-${version}.jar")
        relocate("org.mariadb.jdbc", "org.mariadb.${rootProject.name.lowercase()}.jdbc")
        //include("org/mariadb/**")
    }
}
