name: DBHandler
version: '${project.version}'
main: com.clanjhoo.dbhandler.DBHandler
api-version: 1.18
load: STARTUP
authors: [ Mowstyl ]
description: Handles creating tables as well as loading and storing them
website: https://clanjhoo.com/
